// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const authBgPng = 'assets/images/auth_bg.png';
  static const journoLogoPng = 'assets/images/journo_logo.png';
  static const onboard1Png = 'assets/images/onboard1.png';
  static const onboard2Png = 'assets/images/onboard2.png';
  static const onboard3Png = 'assets/images/onboard3.png';
}

class AssetsSvgs {

}

